# .chglog/config.yml
sort_tags_by: semver
types:
    - type: feat
      description: Features
      emoji: âœ¨
    - type: fix
      description: Bug Fixes
      emoji: ğŸ›
    - type: docs
      description: Documentation
      emoji: ğŸ“š
    - type: style
      description: Styles
      emoji: ğŸ’„
    - type: refactor
      description: Refactors
      emoji: ğŸ”¨
    - type: perf
      description: Performance Improvements
      emoji: âš¡
    - type: test
      description: Tests
      emoji: âœ…
    - type: chore
      description: Chores
      emoji: ğŸ”§
    - type: build
      description: Build System
      emoji: ğŸ—
    - type: ci
      description: Continuous Integration
      emoji: ğŸ‘·â€â™‚ï¸
    - type: revert
      description: Reverts
      emoji: âª
